MVCProject/Models/Candidate.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSubTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Candidate 
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Full Name is required")]
        public string FullName { get; set; }

        public string Gender { get; set; }

        public int Age { get; set; }

        [Required(ErrorMessage = "Area is required")]
        public string Area { get; set; }

        [Required(ErrorMessage = "City is required")]
        public string City { get; set; }

        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }

        
        public string CV { get; set; }
        public string Image { get; set; }
    }
}

MVCProject/Controllers/CandidateController.cs
using CVSubTask.Models;
using CVSubTask.Services;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using System.Windows.Media.Imaging;

namespace CVSubTask.Controllers
{
    public class CandidateController : Controller
    {
         CVFormTaskEntities _context=new CVFormTaskEntities();
        FileService fileService = new FileService();
        CandidateRepository Repo = new CandidateRepository();
        

        // GET: Candidate
        public ActionResult Index()
        {
            //var candidates = _context.Candidates.AsEnumerable();
            var candidates = Repo.GetAll().AsEnumerable();
            return View(candidates);

        }
        [HttpGet]
        public ActionResult SubmitCV()
        {
            return View();
        }
     
       
        
        [HttpPost]
        public ActionResult SubmitCV(Candidate model,HttpPostedFileBase cv , HttpPostedFileBase img ,string Genders, DateTime ? DateOBirth)
        {
            if (DateOBirth == null)
            {
                ModelState.AddModelError("DateError", "Enter your date of birth");
                return View();
            }

            if (!(fileService.isFileExist(cv)))
            {
                ModelState.AddModelError("FileError", "No File uploaded");
                return View();
            }

            if(!(fileService.isFileExist(img)))
            {
                ModelState.AddModelError("ImageError", "No Image uploaded");
                return View();

            }

            if (!(fileService.isFileSupportedFormat(cv)))
            {
                ModelState.AddModelError("FileError", "Unsupported format, only WORD and PDF are supported");
                return View();
            }

            if (!(fileService.isFileSupportedSize(cv)))                         // larger than 1024*1024
            {
                ModelState.AddModelError("FileError", "file too large, exceeded 1 MB");

                return View();
            }

           


            if (!(fileService.isImageSupported(img)))
            {
                ModelState.AddModelError("ImageError", "Not an image or exceeded 256 X 256 pixel image ");
            }


            string ImageName = Guid.NewGuid() + Path.GetExtension(img.FileName);
            string fullPath = Path.GetFullPath(ImageName);
            

            if (ModelState.IsValid)
            {
                try
                {
                    string FileName = Guid.NewGuid() + Path.GetExtension(cv.FileName);
                    cv.SaveAs(Path.Combine(Server.MapPath("~/Content/Uploads"), FileName));
                    img.SaveAs(Path.Combine(Server.MapPath("~/Content/Uploads/imgs"), ImageName));

                    var today = DateTime.Today;
                    var age = today.Year - DateOBirth.Value.Year;
                    if (age <= 0)
                    {
                        ModelState.AddModelError("DateError", "Invalid");
                        return View();
                    }

                    model.CV = FileName;
                    model.Image = ImageName;
                    model.Gender = Genders;
                    model.Age = age;

                   if(Repo.Add(model)!=null)
                    {
                        ModelState.Clear();
                        model = null;
                        ViewBag.msg = "Added!";
                    }

                    else
                    {
                        return HttpNotFound("Not found");
                    }


                    
                }
                catch (Exception e)
                {
                    ViewBag.msg = "Error Occurred ,try again";
                    return View();
                }

            }
            return View();
        }

        
        public  ActionResult Delete(int id)
        {
            // var can=_context.Candidates.FirstOrDefault(c => c.Id == id);
            var can = Repo.GetbyId(id);
            if (can != null)
            {
                //_context.Candidates.Remove(can);
                //_context.SaveChanges();
                Repo.Delete(id);
                return RedirectToAction("Index");
            }

            else
            {
                return HttpNotFound();
            }
            
        }

        public ActionResult Details(int id)
        {
            var can = Repo.GetbyId(id);
            if (can != null)
            {

                return View(can);
            }

            else
            {
                return HttpNotFound();
            }
        }

        public ActionResult Edit(int id)
        {
            var can = Repo.GetbyId(id);
            if (can != null)
            {

                return View(can);
            }

            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        public ActionResult Edit(Candidate model, HttpPostedFileBase cv, HttpPostedFileBase img, string Genders, DateTime? DateOBirth)
        {
            if (DateOBirth == null)
            {
                ModelState.AddModelError("DateError", "Enter your date of birth");
                return View();
            }


            if (cv == null)
            {
                ModelState.AddModelError("FileError", "No File uploaded");
                return View();
            }

            if (img == null)
            {
                ModelState.AddModelError("ImageError", "No Image uploaded");
                return View();

            }

            if (!(fileService.isFileSupportedFormat(cv)))
            {
                ModelState.AddModelError("FileError", "Unsupported format, only WORD and PDF are supported");
                return View();
            }

            if (!(fileService.isFileSupportedSize(cv)))                         // larger than 1024*1024
            {
                ModelState.AddModelError("FileError", "file too large, exceeded 1 MB");

                return View();
            }


            if (!(fileService.isImageSupported(img)))
            {
                ModelState.AddModelError("ImageError", "Not an image or exceede 256 X 256 pixel image");
            }


            string ImageName = Guid.NewGuid() + Path.GetExtension(img.FileName);
            string fullPath = Path.GetFullPath(ImageName);


            if (ModelState.IsValid)
            {
                try
                {
                    string FileName = Guid.NewGuid() + Path.GetExtension(cv.FileName);
                    cv.SaveAs(Path.Combine(Server.MapPath("~/Content/Uploads"), FileName));
                    img.SaveAs(Path.Combine(Server.MapPath("~/Content/Uploads/imgs"), ImageName));

                    var today = DateTime.Today;
                    var age = today.Year - DateOBirth.Value.Year;
                    if (age <= 0)
                    {
                        ModelState.AddModelError("DateError", "Invalid");
                        return View();
                    }

                    model.CV = FileName;
                    model.Image = ImageName;
                    model.Gender = Genders;
                    model.Age = age;


                   if(Repo.Update(model) != null)
                    {
                        ModelState.Clear();
                        model = null;
                        ViewBag.msg = "updated!";
                    }

                    else
                    {
                        return HttpNotFound("Notfound");
                    }

                    
                }
                catch (Exception e)
                {
                    ViewBag.msg = "Error Occurred ,try again";
                    return View();
                }

            }
            return View();
        }
    }
}

MVCProject/Views/Candidate/Edit.cshtml
@model CVSubTask.Models.Candidate

@{
    ViewBag.Title = "Edit";
}

@if (ViewBag.msg != null)
{
    <span style="color:lightseagreen">
        @ViewBag.msg
    </span>
}


<h2>Edit</h2>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<style>

    body {
        background-color: #f5f5f5;
    }

    .imagePreview {
        width: 100%;
        height: 180px;
        background-position: center center;
        background-color: #fff;
        background-size: cover;
        background-repeat: no-repeat;
        display: inline-block;
        box-shadow: 0px -3px 6px 2px rgba(0,0,0,0.2);
    }

    .btn-primary {
        display: block;
        border-radius: 0px;
        box-shadow: 0px 4px 6px 2px rgba(0,0,0,0.2);
        margin-top: -5px;
    }

    .imgUp {
        margin-bottom: 15px;
    }

    .del {
        position: absolute;
        top: 0px;
        right: 15px;
        width: 30px;
        height: 30px;
        text-align: center;
        line-height: 30px;
        background-color: rgba(255,255,255,0.6);
        cursor: pointer;
    }

    .imgAdd {
        width: 30px;
        height: 30px;
        border-radius: 50%;
        background-color: #4bd7ef;
        color: #fff;
        box-shadow: 0px 0px 2px 1px rgba(0,0,0,0.2);
        text-align: center;
        line-height: 30px;
        margin-top: 0px;
        cursor: pointer;
        font-size: 15px;
    }

    .disabled{
        display:none
    }
</style>


@using (Html.BeginForm("Edit", "Candidate", FormMethod.Post, new { enctype = "multipart/form-data" , onsubmit = "submitVal(event)" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Candidate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="col-6">
            <div class="form-group ">
                <br><div class="container">
                    <div class="row">
                        <div class="col-sm-2 imgUp">
                            <div class="imagePreview"></div>
                            <label class="btn btn-primary">
                                Upload<input type="file" id="imgFile" class="uploadFile img" value="Upload Photo" name="img" accept="image/*" onchange="ValidateImg(event)" style="width: 0px;height: 0px;overflow: hidden;">

                            </label>
                            <span id="imageAlert" style="color:red"> </span>
                            @Html.ValidationMessage("ImageError", new { @class = "text-danger" })           @*for server validation*@
                        </div><!-- col-2 -->
                        <i class="fa fa-plus imgAdd"></i>
                    </div><!-- row -->
                </div><!-- container -->
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.TextBoxFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", id = "FullName" } })
                <span id="nameAlert" style="color:red"> </span>
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">

            @Html.Label("Gender", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-1">
                <span id="genderAlert" style="color:red"> </span>
                <select class="form-control"  id="CandidateGender" name="Genders" onchange="genderChange()">
                    <option value="No select" selected disabled>--Select your gender--</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
            </div>


        </div>

        <div class="form-group">
            @Html.Label("Date of Birth", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                <input type="date" id="dateInput" name="DateOBirth" onchange="dateChange()"/>
                <span id="dateAlert" style="color:red"> </span>
                @Html.ValidationMessage("DateError", new { @class = "text-danger" })
            </div>


        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Area, new { htmlAttributes = new { @class = "form-control", Type = "text" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.City, new { htmlAttributes = new { @class = "form-control", Type = "text" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* @Html.EditorFor(model => model.CV, new { htmlAttributes = new { @class = "form-control", Type = "file", name = "mohammed" } })*@
                <input type="file" id="cvFile" name="cv" accept=".pdf,.docx" onchange="validateFile()" />     @*for client validation*@
                @Html.ValidationMessage("FileError", new { @class = "text-danger" })           @*for server validation*@
                <span id="fileAlert" style="color:red"> </span>
            </div>
        </div>

    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="submitBtn" value="Save" class="btn btn-default"  />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>

    function genderChange() {
        if (document.getElementById("CandidateGender").value != "No select") {
            document.getElementById("genderAlert").innerHTML = "";
        }
    }

    function dateChange() {
        if ($("#dateInput").val() != null) {
            document.getElementById("dateAlert").innerHTML = "";
        }
    }


    function submitVal(event) {

        var imgLength = $("#imgFile")[0].files.length;
        if (imgLength === 0) {
            document.getElementById("imageAlert").innerHTML = "Insert your profile photo";
            event.preventDefault(); 
        }

        var cvLength = $("#cvFile")[0].files.length;
        if (cvLength === 0) {
            document.getElementById("fileAlert").innerHTML = "Insert your cv";
            event.preventDefault();
        }

        var date = $("#dateInput").val();
        if (date === "") {
            document.getElementById("dateAlert").innerHTML = "Date of Birth required";
            event.preventDefault();
        }

        if (document.getElementById("CandidateGender").value == "No select") {
            document.getElementById("genderAlert").innerHTML = "Choose your gender";
            event.preventDefault();
        }
        
        

    }

    $(".imgAdd").click(function () {
        $(this).closest(".row").find('.imgAdd').before('<div class="col-sm-2 imgUp"><div class="imagePreview"></div><label class="btn btn-primary">Upload<input type="file" class="uploadFile img" value="Upload Photo" style="width:0px;height:0px;overflow:hidden;"></label><i class="fa fa-times del"></i></div>');
    });
    $(document).on("click", "i.del", function () {
        $(this).parent().remove();
    });
    $(function () {
        $(document).on("change", ".uploadFile", function () {
            var uploadFile = $(this);
            var files = !!this.files ? this.files : [];
            if (!files.length || !window.FileReader) return; // no file selected, or no FileReader support

            if (/^image/.test(files[0].type)) { // only image file
                var reader = new FileReader(); // instance of the FileReader
                reader.readAsDataURL(files[0]); // read the local file

                reader.onloadend = function () { // set image data as background of div
                    //alert(uploadFile.closest(".upimage").find('.imagePreview').length);
                    uploadFile.closest(".imgUp").find('.imagePreview').css("background-image", "url(" + this.result + ")");
                }
            }

        });
    });


    const ValidateImg = (event) => {            //client

        var type = document.getElementById("imgFile").type;
        if (!(type === "image/jpg" || type === "image/png" || type === "image/gif" || type === "image/jpeg")) {
            
            document.getElementById("imageAlert").innerHTML = "not an image";
        }
        let img = new Image()
        img.src = window.URL.createObjectURL(event.target.files[0])
        img.onload = () => {

            console.log(event.target.files[0])
            if ((img.width <= 256 && img.height <= 256)) {
                document.getElementById("imageAlert").innerHTML = "";

                return true;
            }
            else {

                document.getElementById("imageAlert").innerHTML = "Incorrect size not exceed 256x256";
                return false;
            }

        }
    }

    function validateFile() {   //at client

        var cvLength = $("#cvFile")[0].files.length;
        if (cvLength != 0) {
            document.getElementById("fileAlert").innerHTML = "";
            if ($("#cvFile")[0].files[0].size > 1000000) {
                document.getElementById("fileAlert").innerHTML = "File too big (max 1 MB)";
            }

            var parts = $("#cvFile")[0].files[0].name.split('.');
            console.log(parts[1])
            if (!(parts[1].toLowerCase() === "pdf" || parts[1].toLowerCase() === "docx")) {
                document.getElementById("fileAlert").innerHTML = "Only word and pdf are supported";
            }

        }

    }




</script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MVCProject/Views/Candidate/SubmitCV.cshtml
@model CVSubTask.Models.Candidate

@{
    ViewBag.Title = "SubmitCV";
}


<h2>SubmitCV</h2>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<style>

    body {
        background-color: #f5f5f5;
    }

    .imagePreview {
        width: 100%;
        height: 180px;
        background-position: center center;
        background-color: #fff;
        background-size: cover;
        background-repeat: no-repeat;
        display: inline-block;
        box-shadow: 0px -3px 6px 2px rgba(0,0,0,0.2);
    }

    .btn-primary {
        display: block;
        border-radius: 0px;
        box-shadow: 0px 4px 6px 2px rgba(0,0,0,0.2);
        margin-top: -5px;
    }

    .imgUp {
        margin-bottom: 15px;
    }

    .del {
        position: absolute;
        top: 0px;
        right: 15px;
        width: 30px;
        height: 30px;
        text-align: center;
        line-height: 30px;
        background-color: rgba(255,255,255,0.6);
        cursor: pointer;
    }

    .imgAdd {
        width: 30px;
        height: 30px;
        border-radius: 50%;
        background-color: #4bd7ef;
        color: #fff;
        box-shadow: 0px 0px 2px 1px rgba(0,0,0,0.2);
        text-align: center;
        line-height: 30px;
        margin-top: 0px;
        cursor: pointer;
        font-size: 15px;
    }
</style>

@if (ViewBag.msg != null)
{
    <span style="color:lightseagreen">
        @ViewBag.msg
    </span>
}

@using (Html.BeginForm("SubmitCV", "Candidate", FormMethod.Post, new { enctype = "multipart/form-data", name="myForm",onsubmit = "submitVal(event)" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Candidate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="col-6">

            <div class="col-6">
                <div class="form-group ">
                    <br><div class="container">
                        <div class="row">
                            <div class="col-sm-2 imgUp">
                                <div class="imagePreview"></div>
                                <label class="btn btn-primary">
                                    Upload<input type="file" id="imgFile" class="uploadFile img" value="Upload Photo" name="img" accept="image/*" onchange="ValidateImg(event)" style="width: 0px;height: 0px;overflow: hidden;">

                                </label>
                                <span id="imageAlert" style="color:red"> </span>
                                @Html.ValidationMessage("ImageError", new { @class = "text-danger" })           @*for server validation*@
                            </div><!-- col-2 -->
                        <i class="fa fa-plus imgAdd"></i>
                    </div><!-- row -->
                </div><!-- container -->
            </div>

        </div>




        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.FullName, new {  htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">

            @Html.Label("Gender", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-1">
                <span id="genderAlert" style="color:red"> </span>
                <select class="form-control" id="CandidateGender" name="Genders" onchange="genderChange()">
                    <option value="No select" selected disabled>--Select your gender--</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>


            </div>


        </div>

        <div class="form-group">
            @Html.Label("Date of Birth", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                <input type="date" id="dateInput" name="DateOBirth" onchange="dateChange()" />
                <span id="dateAlert" style="color:red"> </span>
                @Html.ValidationMessage("DateError", new { @class = "text-danger" })
            </div>


        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control", Type = "text" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", Type = "text" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* @Html.EditorFor(model => model.CV, new { htmlAttributes = new { @class = "form-control", Type = "file", name = "mohammed" } })*@
                <input type="file" id="cvFile" name="cv" accept=".pdf,.docx" onchange="validateFile()" />     @*for client validation*@
                @Html.ValidationMessage("FileError", new { @class = "text-danger" })           @*for server validation*@
                <span id="fileAlert" style="color:red"> </span>
            </div>
            </div>

        </div>

       



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit"  class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script>

    function genderChange() {
        if (document.getElementById("CandidateGender").value != "No select") {
            document.getElementById("genderAlert").innerHTML = "";
        }
    }

   
    function dateChange() {
        if ($("#dateInput").val() != null) {
            document.getElementById("dateAlert").innerHTML = "";
        }
    }

    

    function submitVal(event) {

        var imgLength = $("#imgFile")[0].files.length;
        if (imgLength === 0) {
            document.getElementById("imageAlert").innerHTML = "Insert your profile photo";
            event.preventDefault();
        }

        var cvLength = $("#cvFile")[0].files.length;
        if (cvLength === 0) {
            document.getElementById("fileAlert").innerHTML = "Insert your cv";
            event.preventDefault();
        }

        var date = $("#dateInput").val();
        if (date === "") {
            document.getElementById("dateAlert").innerHTML = "Date of Birth required";
            event.preventDefault();
        }

        if (document.getElementById("CandidateGender").value == "No select") {
            document.getElementById("genderAlert").innerHTML = "Choose your gender";
            event.preventDefault();
        }

    }

    $(".imgAdd").click(function () {
        $(this).closest(".row").find('.imgAdd').before('<div class="col-sm-2 imgUp"><div class="imagePreview"></div><label class="btn btn-primary">Upload<input type="file" class="uploadFile img" value="Upload Photo" style="width:0px;height:0px;overflow:hidden;"></label><i class="fa fa-times del"></i></div>');
    });
    $(document).on("click", "i.del", function () {
        $(this).parent().remove();
    });
    $(function () {
        $(document).on("change", ".uploadFile", function () {
            var uploadFile = $(this);
            var files = !!this.files ? this.files : [];
            if (!files.length || !window.FileReader) return; // no file selected, or no FileReader support

            if (/^image/.test(files[0].type)) { // only image file
                var reader = new FileReader(); // instance of the FileReader
                reader.readAsDataURL(files[0]); // read the local file

                reader.onloadend = function () { // set image data as background of div
                    //alert(uploadFile.closest(".upimage").find('.imagePreview').length);
                    uploadFile.closest(".imgUp").find('.imagePreview').css("background-image", "url(" + this.result + ")");
                }
            }

        });
    });

    const ValidateImg = (event) => {         //client

        var type = document.getElementById("imgFile").type;
        if (!(type === "image/jpg" || type === "image/png" || type === "image/gif" || type === "image/jpeg")) {

            document.getElementById("imageAlert").innerHTML = "not an image";
        }
        let img = new Image()
        img.src = window.URL.createObjectURL(event.target.files[0])
        img.onload = () => {

            console.log(event.target.files[0])
            if ((img.width <= 256 && img.height <= 256)) {
                document.getElementById("imageAlert").innerHTML = "";

                return true;
            }
            else {

                document.getElementById("imageAlert").innerHTML = "Incorrect size not exceed 256x256";
                return false;
            }

        }
    }

    function validateFile() {   //at client

        var cvLength = $("#cvFile")[0].files.length;
        if (cvLength != 0) {
            document.getElementById("fileAlert").innerHTML = "";
            if ($("#cvFile")[0].files[0].size > 1000000) {
                document.getElementById("fileAlert").innerHTML = "File too big (max 1 MB)";
            }

            var parts = $("#cvFile")[0].files[0].name.split('.');
            console.log(parts[1])
            if (!(parts[1].toLowerCase() === "pdf" || parts[1].toLowerCase() === "docx")) {
                document.getElementById("fileAlert").innerHTML = "Only word and pdf are supported";
            }

        }

    }







</script>


<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>